name: Connect 4
on:
  issues:
    types: [opened]
  workflow_dispatch:
  push:
    branches:
    - main
permissions:
  contents: write
jobs:
  connect4:
    runs-on: ubuntu-latest
    steps:
      - uses: simonecorsi/connect4-readme-action@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
