name: Connect 4
on:
  issue_comment:
    types: [created]
jobs:
  connect4:
    runs-on: ubuntu-latest
    steps:
      - uses: simonecorsi/connect4-readme-action@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
